// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uacbkjnimjzsoltegdhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhY2Jram5pbWp6c29sdGVnZGhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNTc3NDQsImV4cCI6MjA1NTczMzc0NH0.uhvNAVx5wDk7xLjuoILNIyQrcnkYvKE5sMjE1DxB0WA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);